version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
  harvester:
    build: harvester/Dockerfile
    depends_on:
      - broker-rabbitmq
    env_file: harvester/local.env
  injector:
    build: injector/Dockerfile
    depends_on:
      - broker-rabbitmq
      - mongodb
    environment:
      - MONGO_URI=mongodb://localhost:27017/myDatabase
volumes:
    dbdata6:

networks:
  default:
    driver: bridge
