on:
  push:
    paths:
      - 'rabbit/**'
      - 'config.py'
      - 'poetry.lock'
      - 'pyproject.toml'

jobs:
  sync-injector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy data
        run: |
          make preapre-injector
      - name: Commit changes
        uses: devops-infra/action-commit-push@master
        with:
            github_token: "${{ secrets.GITHUB_TOKEN }}"
            add_timestamp: true
            commit_prefix: "[AUTO]"
            commit_message: "Update injector"
            force: true
